-- Run this in Supabase SQL editor

-- Storage setup for profile avatars.
-- The app stores user avatars under profile-images/<auth.uid()>/<filename>.
insert into storage.buckets (id, name, public)
values ('profile-images', 'profile-images', true)
on conflict (id) do update set public = true, name = excluded.name;

drop policy if exists "Public read profile images" on storage.objects;
create policy "Public read profile images"
on storage.objects
for select
using (bucket_id = 'profile-images');

drop policy if exists "Users upload own profile images" on storage.objects;
create policy "Users upload own profile images"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'profile-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users update own profile images" on storage.objects;
create policy "Users update own profile images"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'profile-images'
  and (storage.foldername(name))[1] = auth.uid()::text
)
with check (
  bucket_id = 'profile-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

drop policy if exists "Users delete own profile images" on storage.objects;
create policy "Users delete own profile images"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'profile-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create table if not exists public.users (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.workspaces (
  id bigint generated by default as identity primary key,
  name text not null,
  owner_user_id bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.workspace_members (
  id bigint generated by default as identity primary key,
  workspace_id bigint not null references public.workspaces(id) on delete cascade,
  user_id bigint references public.users(id) on delete cascade,
  role text not null default 'member',
  status text not null default 'active',
  invited_email text,
  invited_by bigint references public.users(id) on delete set null,
  joined_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.workspace_members
drop constraint if exists workspace_members_role_check;

alter table public.workspace_members
add constraint workspace_members_role_check
check (role in ('owner', 'admin', 'member'));

alter table public.workspace_members
drop constraint if exists workspace_members_status_check;

alter table public.workspace_members
add constraint workspace_members_status_check
check (status in ('pending', 'active'));

create unique index if not exists workspace_members_workspace_user_idx
on public.workspace_members (workspace_id, user_id);

create unique index if not exists workspace_members_workspace_invited_email_idx
on public.workspace_members (workspace_id, invited_email);

create index if not exists workspace_members_workspace_status_idx
on public.workspace_members (workspace_id, status, created_at desc);

create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  workspace_id bigint references public.workspaces(id) on delete cascade,
  title text not null,
  content text not null default '',
  video_url text,
  video_type text,
  video_summary text,
  category text not null default 'idea',
  tags text[] not null default '{}',
  pinned boolean not null default false,
  editor_mode text not null default 'rich',
  created_at timestamptz not null default now()
);

alter table public.notes
add column if not exists workspace_id bigint references public.workspaces(id) on delete cascade;

alter table public.notes
drop constraint if exists notes_category_check;

alter table public.notes
add constraint notes_category_check
check (category in ('idea', 'bug', 'meeting', 'project'));

alter table public.notes
drop constraint if exists notes_editor_mode_check;

alter table public.notes
add constraint notes_editor_mode_check
check (editor_mode in ('rich', 'markdown'));

create index if not exists notes_tags_gin_idx
on public.notes using gin (tags);

create table if not exists public.video_timestamps (
  id bigint generated by default as identity primary key,
  note_id bigint not null references public.notes(id) on delete cascade,
  timestamp_seconds integer not null check (timestamp_seconds >= 0),
  text text not null,
  created_at timestamptz not null default now()
);

create index if not exists video_timestamps_note_created_idx
on public.video_timestamps (note_id, created_at desc);

create table if not exists public.note_attachments (
  id bigint generated by default as identity primary key,
  note_id bigint not null references public.notes(id) on delete cascade,
  file_name text not null,
  file_type text,
  file_url text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  status text not null default 'todo',
  user_id bigint references public.users(id) on delete cascade,
  workspace_id bigint references public.workspaces(id) on delete cascade,
  assigned_to bigint references public.users(id) on delete set null,
  due_date date,
  generated_by text,
  created_at timestamptz not null default now()
);

alter table public.tasks
add column if not exists workspace_id bigint references public.workspaces(id) on delete cascade;

alter table public.tasks
add column if not exists assigned_to bigint references public.users(id) on delete set null;

alter table public.tasks
add column if not exists generated_by text;

create table if not exists public.usage_events (
  id bigint generated by default as identity primary key,
  workspace_id bigint references public.workspaces(id) on delete cascade,
  user_id bigint references public.users(id) on delete cascade,
  event_type text not null,
  created_at timestamptz not null default now()
);

create index if not exists usage_events_workspace_created_idx
on public.usage_events (workspace_id, created_at desc);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  product text not null,
  price numeric(12,2) not null default 0,
  customer text not null,
  date timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2) not null default 0,
  stock integer not null default 0
);

create table if not exists public.ai_conversations (
  id bigint generated by default as identity primary key,
  user_id bigint references public.users(id) on delete cascade,
  title text not null default 'New chat',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ai_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.ai_conversations(id) on delete cascade,
  role text not null,
  content text not null,
  task text,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  workspace_id bigint references public.workspaces(id) on delete cascade,
  user_id bigint references public.users(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null default '',
  entity_type text,
  entity_id bigint,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.notifications
add column if not exists workspace_id bigint references public.workspaces(id) on delete cascade;

create table if not exists public.activity_logs (
  id bigint generated by default as identity primary key,
  workspace_id bigint references public.workspaces(id) on delete cascade,
  user_id bigint references public.users(id) on delete cascade,
  action_type text not null,
  description text not null,
  entity_type text,
  entity_id bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.activity_logs
add column if not exists workspace_id bigint references public.workspaces(id) on delete cascade;

alter table public.ai_messages
drop constraint if exists ai_messages_role_check;

alter table public.ai_messages
add constraint ai_messages_role_check
check (role in ('user', 'assistant'));

create index if not exists ai_conversations_user_updated_idx
on public.ai_conversations (user_id, updated_at desc);

create index if not exists ai_messages_conversation_created_idx
on public.ai_messages (conversation_id, created_at asc);

create index if not exists tasks_workspace_created_idx
on public.tasks (workspace_id, created_at desc);

create index if not exists tasks_workspace_status_idx
on public.tasks (workspace_id, status, created_at desc);

create index if not exists tasks_workspace_assigned_idx
on public.tasks (workspace_id, assigned_to);

create index if not exists notes_workspace_created_idx
on public.notes (workspace_id, created_at desc);

create index if not exists notifications_workspace_user_created_idx
on public.notifications (workspace_id, user_id, created_at desc);

create index if not exists activity_logs_workspace_created_idx
on public.activity_logs (workspace_id, created_at desc);

do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'tasks'
      and column_name = 'status'
  ) then
    update public.tasks
    set status = 'in_progress'
    where lower(status) = 'progress';
  end if;
end $$;

do $$
declare
  workspace_row record;
begin
  for workspace_row in
    select u.id as user_id, coalesce(u.name, split_part(u.email, '@', 1), 'My') || ' Workspace' as workspace_name
    from public.users u
    where not exists (
      select 1
      from public.workspace_members wm
      where wm.user_id = u.id
        and wm.status = 'active'
    )
  loop
    insert into public.workspaces (name, owner_user_id)
    values (workspace_row.workspace_name, workspace_row.user_id);

    insert into public.workspace_members (
      workspace_id,
      user_id,
      role,
      status,
      invited_email,
      invited_by,
      joined_at
    )
    values (
      currval(pg_get_serial_sequence('public.workspaces', 'id')),
      workspace_row.user_id,
      'owner',
      'active',
      (select email from public.users where id = workspace_row.user_id),
      workspace_row.user_id,
      now()
    )
    on conflict do nothing;
  end loop;
end $$;

update public.notes n
set workspace_id = wm.workspace_id
from public.workspace_members wm
where n.workspace_id is null
  and wm.user_id = n.user_id
  and wm.status = 'active';

update public.tasks t
set workspace_id = wm.workspace_id,
    assigned_to = coalesce(t.assigned_to, t.user_id)
from public.workspace_members wm
where t.workspace_id is null
  and wm.user_id = t.user_id
  and wm.status = 'active';

update public.notifications n
set workspace_id = wm.workspace_id
from public.workspace_members wm
where n.workspace_id is null
  and wm.user_id = n.user_id
  and wm.status = 'active';

update public.activity_logs a
set workspace_id = wm.workspace_id
from public.workspace_members wm
where a.workspace_id is null
  and wm.user_id = a.user_id
  and wm.status = 'active';
