const BACKEND_API_BASE_URL = process.env.BACKEND_API_BASE_URL || "http://127.0.0.1:5000";
const BACKEND_AI_URL = `${BACKEND_API_BASE_URL.replace(/\/+$/, "")}/ai/process`;
const OPENAI_API_KEY = process.env.OPENAI_API_KEY || "";
const OPENAI_MODEL = process.env.OPENAI_MODEL || "gpt-4.1-mini";
const OPENAI_API_URL = process.env.OPENAI_API_URL || "https://api.openai.com/v1/chat/completions";
const OPENAI_ENABLED = process.env.OPENAI_ENABLED === "true";
const HF_API_TOKEN = process.env.HF_API_TOKEN || "";
const HF_MODEL_ID = process.env.HF_MODEL_ID || "facebook/bart-large-cnn";
const HF_ROUTER_BASE_URL =
  process.env.HF_ROUTER_BASE_URL || "https://router.huggingface.co/hf-inference/models";

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ result: "Method not allowed." });
  }

  const task = String(req.body?.task || "").trim().toLowerCase();
  const text = String(req.body?.text || "").trim();
  const history = normalizeHistory(req.body?.history);

  if (!text) {
    return res.status(400).json({ result: "No text provided." });
  }

  try {
    if (task === "chat") {
      return res.status(400).json({
        result:
          "General chat is not supported in this workspace. Use Summarize, Tasks, or Improve instead."
      });
    }

    if (task === "summarize") {
      const summary = await summarizeText(text);
      return res.status(200).json({ result: summary });
    }

    if (task === "tasks") {
      const tasks = await taskText(text);
      return res.status(200).json({ result: tasks });
    }

    if (task === "improve") {
      const improved = await improveText(text);
      return res.status(200).json({ result: improved });
    }

    const backendResult = await callBackend(task, text);
    return res.status(200).json({ result: backendResult });
  } catch (error) {
    return res.status(502).json({
      result:
        error?.message ||
        "AI request failed. Verify Hugging Face or backend configuration and try again."
    });
  }
}

async function summarizeText(text) {
  if (OPENAI_ENABLED && OPENAI_API_KEY) {
    return callOpenAI({
      system:
        "Summarize the user's notes clearly and concisely. Prefer short paragraphs or bullets. Preserve important facts and action items.",
      userText: text
    });
  }

  return generateSummary(text);
}

async function taskText(text) {
  if (OPENAI_ENABLED && OPENAI_API_KEY) {
    return callOpenAI({
      system:
        "Convert the user's request into a clear actionable task list. Use a numbered list. Be specific and practical.",
      userText: text
    });
  }

  return generateTaskPlan(text);
}

async function improveText(text) {
  if (OPENAI_ENABLED && OPENAI_API_KEY) {
    return callOpenAI({
      system:
        "Improve the user's writing for clarity, grammar, and professionalism while preserving the original meaning. Return only the improved text.",
      userText: text
    });
  }

  return improveDraft(text);
}

async function callHuggingFaceSummary(text) {
  const url = buildHuggingFaceUrl();
  const response = await fetch(url, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${HF_API_TOKEN}`
    },
    body: JSON.stringify({
      inputs: text,
      parameters: {
        max_new_tokens: 180,
        min_length: 30,
        do_sample: false
      },
      options: {
        wait_for_model: true
      }
    })
  });

  const data = await parseJsonSafely(response);
  if (!response.ok) {
    throw new Error(extractErrorMessage(data) || "Hugging Face summarization failed.");
  }

  const result = extractSummary(data);
  if (!result) {
    throw new Error("No summary was returned by the AI model.");
  }

  return result;
}

async function callOpenAI({ system, userText, history = [] }) {
  const messages = [
    { role: "system", content: system },
    ...history.map((item) => ({
      role: item.role,
      content: item.content
    })),
    { role: "user", content: userText }
  ];

  const response = await fetch(OPENAI_API_URL, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${OPENAI_API_KEY}`
    },
    body: JSON.stringify({
      model: OPENAI_MODEL,
      messages,
      temperature: 0.4
    })
  });

  const data = await parseJsonSafely(response);
  const result = extractOpenAIText(data);

  if (!response.ok) {
    throw new Error(result || extractErrorMessage(data) || "OpenAI request failed.");
  }

  if (!result) {
    throw new Error("No response generated by OpenAI.");
  }

  return result;
}

async function callBackend(task, text, history = []) {
  const response = await fetch(BACKEND_AI_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ task, text, history })
  });

  const data = await parseJsonSafely(response);
  const result = extractSummary(data);

  if (!response.ok) {
    throw new Error(result || extractErrorMessage(data) || "Backend AI request failed.");
  }

  if (!result) {
    throw new Error("No response generated.");
  }

  return result;
}

function buildHuggingFaceUrl() {
  const base = HF_ROUTER_BASE_URL.replace(/\/+$/, "");
  return base.endsWith(HF_MODEL_ID) ? base : `${base}/${HF_MODEL_ID}`;
}

function normalizeHistory(value) {
  if (!Array.isArray(value)) return [];
  return value
    .map((item) => ({
      role: String(item?.role || "").trim().toLowerCase(),
      content: String(item?.content || "").trim()
    }))
    .filter((item) => ["user", "assistant"].includes(item.role) && item.content)
    .slice(-12);
}

async function parseJsonSafely(response) {
  try {
    return await response.json();
  } catch {
    return null;
  }
}

function extractSummary(data) {
  if (!data) return "";
  if (typeof data === "string") return data.trim();

  if (Array.isArray(data)) {
    for (const item of data) {
      const summary =
        item?.summary_text || item?.generated_text || item?.text || item?.answer || "";
      if (summary) return String(summary).trim();
    }
  }

  return String(
    data.summary_text || data.generated_text || data.text || data.answer || data.result || ""
  ).trim();
}

function extractOpenAIText(data) {
  if (!data) return "";

  const messageContent = data?.choices?.[0]?.message?.content;
  if (typeof messageContent === "string") {
    return messageContent.trim();
  }

  if (Array.isArray(messageContent)) {
    const text = messageContent
      .map((item) => item?.text || "")
      .join("")
      .trim();
    if (text) return text;
  }

  return String(data?.output_text || "").trim();
}

function extractErrorMessage(data) {
  if (!data) return "";
  if (typeof data === "string") return data.trim();
  return String(data?.error?.message || data.error || data.message || data.detail || "").trim();
}

function generateSummary(text) {
  const raw = String(text || "");
  const normalized = raw.replace(/\s+/g, " ").trim();
  if (!normalized) {
    throw new Error("Please provide text to summarize.");
  }

  const bulletMatches = raw
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter((line) => /^[-*]\s+/.test(line))
    .map((line) => line.replace(/^[-*]\s+/, "").trim())
    .filter(Boolean);

  if (bulletMatches.length) {
    return `Summary:\n${bulletMatches.slice(0, 6).map((item) => `- ${capitalizeSentence(item)}`).join("\n")}`;
  }

  const cleaned = normalized.replace(/^(meeting notes|notes|summary)\s*:\s*/i, "").trim();
  const parts = cleaned
    .split(/,|;|\band\b|(?<=[.!?])\s+(?=(?:also|then|next|finally|after that|rahul|check|confirm|prepare|fix|finalize)\b)/gi)
    .map((item) => String(item || "").replace(/\s+/g, " ").trim())
    .filter(Boolean);

  if (parts.length >= 2) {
    const bullets = parts.slice(0, 6).map((item) => `- ${capitalizeSentence(item)}`);
    return `Summary:\n${bullets.join("\n")}`;
  }

  const sentences = cleaned
    .split(/(?<=[.!?])\s+/)
    .map((item) => item.trim())
    .filter(Boolean);

  if (sentences.length > 1) {
    return `Summary:\n- ${sentences.slice(0, 3).map(capitalizeSentence).join("\n- ")}`;
  }

  return `Summary:\n- ${capitalizeSentence(cleaned)}`;
}

function capitalizeSentence(value) {
  const text = String(value || "")
    .trim()
    .replace(/^(also|then|next|finally|after that)\s+/i, "")
    .replace(/[.!?]+$/, "");
  if (!text) return "";
  return text.charAt(0).toUpperCase() + text.slice(1);
}

function generateTaskPlan(text) {
  const normalized = String(text || "").replace(/\s+/g, " ").trim();
  if (!normalized) {
    throw new Error("Please provide text to convert into tasks.");
  }

  const subject = normalized
    .replace(/^(create|generate|make|give)\s+(a\s+)?(project\s+plan|task\s+list|tasks)\s+(for\s+)?/i, "")
    .replace(/^(project\s+plan|task\s+list|tasks)\s+(for\s+)?/i, "")
    .trim() || "the requested project";

  const lower = subject.toLowerCase();
  const tasks = [
    `Define the scope, users, and success criteria for ${subject}.`,
    `List the core features and prioritize the MVP for ${subject}.`,
    `Create wireframes and user flows for the main screens.`,
    `Set up the project structure, environment variables, and deployment plan.`,
    `Build authentication and user account flows.`,
    `Implement the main data models, APIs, and database schema.`,
    `Develop the primary UI and connect it to the backend services.`,
    `Test the main user flows, edge cases, and error handling.`,
    `Prepare launch tasks, documentation, and post-release improvements.`
  ];

  if (lower.includes("ai productivity app")) {
    return [
      "1. Define target users, core pain points, and success metrics for the AI productivity app.",
      "2. Finalize the MVP scope: notes, tasks, AI summary, AI writing improvement, and analytics.",
      "3. Design user flows and wireframes for onboarding, dashboard, notes, tasks, and AI tools.",
      "4. Set up the frontend, backend, Supabase schema, authentication, and environment configuration.",
      "5. Build notes management: create, edit, categorize, tag, pin, attach files, and delete notes.",
      "6. Build task management: create tasks, edit titles, move status, and delete tasks.",
      "7. Integrate AI tools for summarize, task generation, and writing improvement with clear error handling.",
      "8. Add saved history for AI requests and connect the UI to the supporting API routes.",
      "9. Test core flows end to end, including auth, notes, tasks, AI requests, and failure states.",
      "10. Prepare release: polish UI, add documentation, seed demo data, and deploy the app."
    ].join("\n");
  }

  return tasks.map((item, index) => `${index + 1}. ${item}`).join("\n");
}

function improveDraft(text) {
  const normalized = String(text || "").replace(/\s+/g, " ").trim();
  if (!normalized) {
    throw new Error("Please provide text to improve.");
  }

  let improved = normalized
    .replace(/\bi\b/g, "I")
    .replace(/\bim\b/gi, "I'm")
    .replace(/\bdont\b/gi, "don't")
    .replace(/\bcant\b/gi, "can't")
    .replace(/\bwont\b/gi, "won't")
    .replace(/\bneed finish\b/gi, "need to finish")
    .replace(/\bneed fix\b/gi, "need to fix")
    .replace(/\bneed check\b/gi, "need to check")
    .replace(/\bneed complete\b/gi, "need to complete")
    .replace(/\bfinish dashboard\b/gi, "finish the dashboard")
    .replace(/\bquick\b/gi, "quickly")
    .replace(/\bevery thing\b/gi, "everything")
    .replace(/\balso need to test\b/gi, "also test")
    .replace(/\band also\b/gi, "and")
    .replace(/\bbefore demo\b/gi, "before the demo")
    .replace(/\bquickly and also\b/gi, "quickly and")
    .replace(/\buser interface\b/gi, "user interface")
    .replace(/\s+,/g, ",")
    .replace(/\s+\./g, ".")
    .replace(/\s+/g, " ")
    .trim();

  improved = improved
    .replace(/\bneed to ([a-z]+) quickly and also test\b/gi, "need to $1 quickly and test")
    .replace(/\bneed to ([a-z]+) quickly and test\b/gi, "need to $1 quickly and test")
    .replace(/\bneed to ([a-z]+) quickly\b/gi, "need to $1 quickly")
    .replace(/\band test everything before the demo\b/gi, "and test everything before the demo")
    .replace(/\balso test everything\b/gi, "test everything")
    .replace(/\bneed to test everything\b/gi, "test everything");

  improved = improved.charAt(0).toUpperCase() + improved.slice(1);
  if (!/[.!?]$/.test(improved)) {
    improved += ".";
  }

  return improved;
}
